import { Award, Heart, Sprout, Stars } from 'lucide-react';
import { IMAGES } from '../app/lib/data';
import { Reveal } from './ui/Reveal';
import { SectionHeading } from './ui/SectionHeading';
import { ImageFrame } from './ImageFrame';

const milestones = [{ year: '1998', text: 'Savora opens as a twelve-seat chef’s atelier.' }, { year: '2006', text: 'First Michelin star awarded for our modern French kitchen.' }, { year: '2017', text: 'A second star and a new home in the heart of the city.' }, { year: '2025', text: 'Named among the World’s 50 Best discovery restaurants.' }];
const values = [{ icon: Sprout, title: 'Season-led', text: 'Menus begin at the market, guided by the purest expression of every ingredient.' }, { icon: Heart, title: 'Generous', text: 'Precision and warmth belong at the same table — every guest is truly seen.' }, { icon: Stars, title: 'Restlessly curious', text: 'We honour classic technique while pursuing the unexpected at every service.' }];

export function AboutExperience() {
  return <><section className="container py-20 lg:py-28"><div className="grid items-center gap-14 lg:grid-cols-2"><Reveal><div className="overflow-hidden rounded-[2rem] border border-white/10"><ImageFrame src={IMAGES.diningRoom} alt="Savora's warmly lit dining room" className="h-[32rem] w-full object-cover" /></div></Reveal><div><SectionHeading align="left" eyebrow="A place with a pulse" title={<>A legacy written in flavor.</>} /><Reveal delay={0.15}><div className="mt-6 space-y-5 leading-relaxed text-beige-muted"><p>In 1998, Laurent Dubois opened Savora with a modest belief: the most remarkable meals are at once precise and deeply human. Twenty-five years later, that idea remains at the centre of every service.</p><p>Our kitchen moves to the rhythm of the seasons, our cellar with the rarest stories, and our dining room with the soft hum of a night unfolding exactly as it should.</p></div></Reveal></div></div></section>
    <section className="border-y border-white/5 bg-ink-soft py-20 lg:py-28"><div className="container"><SectionHeading eyebrow="The timeline" title={<>Twenty-five years of intention</>} /><div className="mx-auto mt-16 max-w-3xl border-l border-gold/30 pl-7 sm:pl-10">{milestones.map((item, index) => <Reveal key={item.year} delay={index * 0.1}><div className="relative pb-10 last:pb-0"><span className="absolute -left-[35px] top-1 h-3 w-3 rounded-full border-2 border-ink-soft bg-gold sm:-left-12" /><p className="font-heading text-2xl text-gold">{item.year}</p><p className="mt-2 text-beige-muted">{item.text}</p></div></Reveal>)}</div></div></section>
    <section className="container py-20 lg:py-28"><div className="grid items-center gap-14 lg:grid-cols-[0.85fr_1fr]"><Reveal><ImageFrame src={IMAGES.chef} alt="Chef Laurent Dubois in the Savora kitchen" className="h-[38rem] w-full rounded-[2rem] border border-white/10 object-cover" /></Reveal><div><SectionHeading align="left" eyebrow="Meet the chef" title={<>Laurent Dubois</>} description="Executive Chef & Founder" /><Reveal delay={0.15}><blockquote className="mt-7 font-heading text-2xl italic leading-snug text-cream">“Technique makes a dish correct. Feeling makes it impossible to forget.”</blockquote><p className="mt-6 leading-relaxed text-beige-muted">From Lyon to Kyoto and now New York, Laurent’s career has been defined by a profound respect for place, product and the people gathered around a table.</p><div className="mt-8 flex gap-8"><div><p className="font-heading text-3xl text-gold">2</p><p className="mt-1 text-xs uppercase tracking-widest text-beige-muted">Michelin stars</p></div><div><p className="font-heading text-3xl text-gold">30</p><p className="mt-1 text-xs uppercase tracking-widest text-beige-muted">Years of craft</p></div></div></Reveal></div></div></section>
    <section className="border-y border-white/5 bg-ink-soft py-20 lg:py-28"><div className="container"><div className="grid gap-14 lg:grid-cols-[1fr_0.85fr]"><div><SectionHeading align="left" eyebrow="Our people" title={<>A brigade built on care</>} /><Reveal><p className="mt-6 max-w-xl leading-relaxed text-beige-muted">Our team comes from seven countries, but shares one language: hospitality with soul. From the first welcome to the last farewell, every exchange is a quiet expression of care.</p></Reveal><Reveal delay={0.12}><ImageFrame src={IMAGES.team} alt="Savora's culinary team preparing dinner" className="mt-8 h-72 w-full rounded-3xl border border-white/10 object-cover" /></Reveal></div><div className="grid gap-5">{values.map((value, index) => <Reveal key={value.title} delay={index * 0.1}><div className="rounded-3xl border border-white/8 bg-ink-card p-7"><value.icon className="h-7 w-7 text-gold" /><h3 className="mt-4 font-heading text-xl text-cream">{value.title}</h3><p className="mt-2 text-sm leading-relaxed text-beige-muted">{value.text}</p></div></Reveal>)}</div></div><Reveal><div className="mt-16 flex flex-wrap items-center justify-center gap-8 border-t border-white/8 pt-10 text-center"><Award className="h-8 w-8 text-gold" /><p className="font-heading text-xl text-cream">Two Michelin Stars · World’s 50 Best Discovery · Wine Spectator Award of Excellence</p></div></Reveal></div></section></>;
}