import Link from 'next/link';
import { ArrowRight, CalendarDays } from 'lucide-react';
import { IMAGES } from '../app/lib/data';
import { Reveal } from './ui/Reveal';
import { ImageFrame } from './ImageFrame';

export function HomeSupplement() {
  return <>
    <section className="container py-24 lg:py-32"><div className="grid items-center gap-12 lg:grid-cols-[0.9fr_1.1fr]"><Reveal><ImageFrame src={IMAGES.diningRoom} alt="Savora's warm, candlelit dining room" className="h-80 w-full rounded-[2rem] border border-white/10 object-cover lg:h-[30rem]" /></Reveal><div><Reveal delay={0.08}><span className="text-xs uppercase tracking-luxe text-gold">Since 1998</span><h2 className="mt-4 max-w-lg font-heading text-4xl leading-tight text-cream sm:text-5xl">A restaurant with a point of view.</h2><p className="mt-5 max-w-xl leading-relaxed text-beige-muted">Savora began as a twelve-seat atelier and grew into one of the city’s most cherished dining rooms. We believe the finest evenings feel both precise and entirely personal.</p><Link href="/about" className="mt-7 inline-flex items-center gap-2 text-sm text-cream transition-colors hover:text-gold">Discover our story <ArrowRight className="h-4 w-4" /></Link></Reveal></div></div></section>
    <section className="container pb-24 lg:pb-32"><div className="grid items-center gap-12 overflow-hidden rounded-[2rem] border border-gold/20 bg-ink-card lg:grid-cols-[1.1fr_0.9fr]"><div className="p-8 sm:p-12"><Reveal><span className="text-xs uppercase tracking-luxe text-gold">A table awaits</span><h2 className="mt-5 max-w-lg font-heading text-4xl leading-tight text-cream sm:text-5xl">Make an evening of it.</h2><p className="mt-5 max-w-md leading-relaxed text-beige-muted">Choose a date, tell us what you’re celebrating, and leave the rest to our team. An exceptional table starts with a simple reservation.</p><Link href="/reservation" className="mt-8 inline-flex items-center gap-2 rounded-full bg-gold px-7 py-3.5 text-sm font-medium text-ink transition-colors hover:bg-gold-soft"><CalendarDays className="h-4 w-4" /> Reserve a table</Link></Reveal></div><Reveal delay={0.1} className="h-full"><ImageFrame src={IMAGES.event} alt="An elegant candlelit table set for a special evening" className="h-72 w-full object-cover lg:h-full" /></Reveal></div></section>
    <section className="container pb-24 lg:pb-32"><div className="flex flex-col justify-between gap-5 sm:flex-row sm:items-end"><Reveal><span className="text-xs uppercase tracking-luxe text-gold">Through our lens</span><h2 className="mt-4 font-heading text-4xl text-cream">A glimpse of Savora</h2></Reveal><Reveal><Link href="/gallery" className="inline-flex items-center gap-2 text-sm text-cream transition-colors hover:text-gold">Explore the gallery <ArrowRight className="h-4 w-4" /></Link></Reveal></div><div className="mt-10 grid gap-4 sm:grid-cols-3"><Reveal><ImageFrame src={IMAGES.diningRoom} alt="Savora's dining room" className="h-80 w-full rounded-3xl border border-white/8 object-cover" /></Reveal><Reveal delay={0.1}><ImageFrame src={IMAGES.dish2} alt="Signature Wagyu dish" className="h-80 w-full rounded-3xl border border-white/8 object-cover" /></Reveal><Reveal delay={0.2}><ImageFrame src={IMAGES.chef} alt="Chef Laurent at work" className="h-80 w-full rounded-3xl border border-white/8 object-cover" /></Reveal></div></section>
  </>;
}